### PR TITLE
[v4r0] add javascript prettier and change 4 space to 2 in exlipse formatter

### PR DESCRIPTION
**Pull request by zmathe**

### CODE REVIEW

**Comment by zmathe** [comment]
@atsareg @fstagni If you make a new release, please include this one as well.

**Comment by fstagni** [comment]
This is quite painful to review. Did you just apply linting?

**Comment by zmathe** [comment]
Yes, I applied the linting and of course I added the required configuration for github action and as well I added prettier configuration

**Comment by atsareg** [comment]
We have already v4r1 with lots of changes that will be in a trivial conflict with this PR. This will be a nightmare to resolve. I would suggest to apply this code beautification to v4r1 and leave v4r0 as it is.

**Comment by zmathe** [comment]
replaced by #372

**Pull request closed without merging**
