### PR TITLE
[v6r18] Network plots in the accounting

### PR DESCRIPTION
**Pull request by hgiemza**
Small change that allows to present the network plots (see DIRACGrid/DIRAC#3083 for details).

### CODE REVIEW

**Comment by fstagni** [comment]
There's a conflicting file: I think this should be merged anyway.

**Comment by zmathe** [comment]
AccountingPlot no longer exists. This can not be merged... It has to be based on #258

**Comment by fstagni** [comment]
@hgiemza please fix this PR, as we'll merge and certify.

**Comment by hgiemza** [comment]
Fixed.

**Pull request merged**
