### PR TITLE
[5.0] Modernise asyncGen and only use new _WebHandler class

### LINKED ISSUE #658: Replace WebHandler with _WebHandler
Apologies if I haven't found where this is was discussed but it seems that we currently have two implementations of the `WebHandler`:

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/Lib/WebHandler.py#L161

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/Lib/WebHandler.py#L401

Most classes seem to be using `_WebHandler` which appears to be a much nicer implementation which delegates every request to a dedicated thread so the `@asyncGen` and ` yield self.threadTask` stuff isn't needed like in:

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/WebApp/handler/SystemAdministrationHandler.py#L91-L92

https://github.com/DIRACGrid/WebAppDIRAC/blob/d70c268ff47fc051ca29fd0415fcaeb0e7587f2a/src/WebAppDIRAC/WebApp/handler/SystemAdministrationHandler.py#L104

Is there a reason why we need both implementations? I think we should just move the legacy style handlers to the new one and delete the old implementation.

### PR DESCRIPTION
**Pull request by chrisburr**
Fixes https://github.com/DIRACGrid/WebAppDIRAC/issues/658

Draft as it is untested and needs #659 

BEGINRELEASENOTES

CHANGE: Modernise asyncGen and only use new _WebHandler class

ENDRELEASENOTES

### CODE REVIEW

**Comment by TaykYoku** [comment]
I would suggest splitting this PR, one PR per handler to speed up viewing and acceptance.

**Comment by chrisburr** [comment]
At the moment it's broken but I'll try to fix it on Monday.

> I would suggest splitting this PR, one PR per handler to speed up viewing and acceptance.

I don't think this would actually help as excluding `WebHandler.py` and `HandlerMgr.py` the changes are very mechanical and just removing `@asyncGen`+`yield self.threadTask` and changing `_WebHandler` to `WebHandler`.

That said, I can make the removal of `asyncGen` and `WebHandler` a separate PR once it's working.

**Comment by TaykYoku** [comment]
This is not entirely true, there are some nuances. The very idea of creating `_WebHandler` based on `BaseRequestHandler` is to change the style of writing handlers. In addition to removing `@asyncGen` + `yield self.threadTask` and changing `_WebHandler` to `WebHandler`, for ex. you need to use `return` instead of `self.finish`, describe **request arguments** via **function annotations**.

I would suggest solving https://github.com/DIRACGrid/WebAppDIRAC/pull/659 first.

Using your list https://github.com/DIRACGrid/WebAppDIRAC/issues/658#issuecomment-1158915346, create a PR by PR for each hadler (as was done before, eg #639, #638 ...). IMHO it's so much easier to test and review, and it can be done in parallel, I can go from the bottom of the list.

`WebHandler` is removed last when all handlers have been ported to `_WebHandler` and tested.

What do you think?

**Comment by chrisburr** [comment]
> This is not entirely true, there are some nuances. The very idea of creating `_WebHandler` based on `BaseRequestHandler` is to change the style of writing handlers. In addition to removing `@asyncGen` + `yield self.threadTask` and changing `_WebHandler` to `WebHandler`, for ex. you need to use `return` instead of `self.finish`, describe **request arguments** via **function annotations**.

Where are the required changes documented? It's really important as it also needs to be done in extensions.

> I would suggest solving #659 first.

I think this is already solved modulo review.

> Using your list [#658 (comment)](https://github.com/DIRACGrid/WebAppDIRAC/issues/658#issuecomment-1158915346), create a PR by PR for each hadler (as was done before, eg #639, #638 ...). IMHO it's so much easier to test and review, and it can be done in parallel, I can go from the bottom of the list.
>
> `WebHandler` is removed last when all handlers have been ported to `_WebHandler` and tested.

As mentioned in https://github.com/DIRACGrid/WebAppDIRAC/issues/658 I think this needs to be done before releasing 5.0 and DIRAC 8.0, which implies it needs to be done before Thursday as that's supposed to be the final hackathon. Once we're done I think we should also rename `_WebHandler` to something else (possibly `WebHandler`) as it currenly looks like an implementation detail.

**Pull request closed without merging**
