### PR TITLE
[v4r0]  bugfixes

### PR DESCRIPTION
**Pull request by zmathe**
BEGINRELEASENOTES

Lib
FIX: import deprecated decorator

ENDRELEASENOTES

### CODE REVIEW

**Comment by atsareg** [comment]
Is it for rel-v4r0 or integration branch ?

**Comment by fstagni** [comment]
rel-v4r0

**Comment by fstagni** [comment]
Wow... I edited the conflicts in the browser and... merged it all?

**Comment by andresailer** [comment]
This fix is also in #334

**Comment by fstagni** [comment]
ah that's why.

**Pull request merged**
