### PR TITLE
[integration] Add monitoring option for data operation for WebApp

### PR DESCRIPTION
**Pull request by rupozzi**
Relating to issue [#4566](https://github.com/DIRACGrid/DIRAC/issues/4566) and pull request [#5807](https://github.com/DIRACGrid/DIRAC/pull/5807) on DIRACGrid/DIRAC repository.
Moving data operation to monitoring so added an option for that on the WebApp.

BEGINRELEASENOTES

NEW: adding monitoring option for pilot submissions

ENDRELEASENOTES

### CODE REVIEW

**Comment by TaykYoku** [comment]
Is `DataOperation` necessary for both `Accounting` and `Monitoring`?

**Comment by fstagni** [comment]
> Is `DataOperation` necessary for both `Accounting` and `Monitoring`?

Yes.

**Review by TaykYoku — APPROVED** [review]
Looks OK to me to merge this when dependencies will be ready

**Comment by TaykYoku** [comment]
If it's not ready yet, please, convert it to draft.

**Comment by fstagni** [comment]
Merging as corresponding PR in DIRAC has been merged.

**Pull request merged**
