### PR TITLE
[v4r3] merge v4r2

### PR DESCRIPTION
**Pull request by TaykYoku**
BEGINRELEASENOTES
v4r3 merge v4r2
ENDRELEASENOTES

### CODE REVIEW

**Comment by chrisburr** [comment]
@TaykYoku Why did you merge this with the labeler disabled, the wrong configuration and not even a mention that the sweeping/lableling needed to be debugged?

**Comment by TaykYoku** [comment]
@chrisburr I disable labeler because of https://github.com/DIRACGrid/WebAppDIRAC/runs/3956177102?check_suite_focus=true.
I think this is the reason why the sweeper didn't work either, so I had to do everything the same way yesterday

**Comment by chrisburr** [comment]
I know why you disabled it, I care about why you merged a broken PR which did nothing except add the sweep/label configuration.

**Comment by TaykYoku** [comment]
I didn't have time to deal with this yesterday, so I turned off the labeler, for all releases. I was planning to figure out the reason why the labeler doesn't work today.
I did not leave it broken, I skip it (https://github.com/DIRACGrid/WebAppDIRAC/pull/580/commits/b87b3fd5532ed9ed2d10811fff64f3ec9f2773cf).

**Pull request merged**
