### PR TITLE
[v4r2] Add new Selection Fields for Component Activity Monitoring in Accounting.js

### PR DESCRIPTION
**Pull request by pujanm**
BEGINRELEASENOTES
This will add new Selection Fields and Group By clauses for Activity Monitoring in the Accounting section of the WebApp.
This change is w.r.t. this [PR](https://github.com/DIRACGrid/DIRAC/pull/4120).
ENDRELEASENOTES

### CODE REVIEW

**Review by zmathe — APPROVED** [review]

**Comment by fstagni** [comment]
This PR needs to target v4r2, once the branch rel-v4r2 will be created.

**Comment by TaykYoku** [comment]
need to rebase

**Comment by fstagni** [comment]
@TaykYoku @atsareg the developer left long time ago, you should just cherry-pick the commits.

**Comment by TaykYoku** [comment]
@fstagni ah OK, then I'll do it

**Comment by TaykYoku** [comment]
This RP was cloned, rebased and merged to rel-v4r2.

**Pull request closed without merging**
