### PR TITLE
[v4r0] add columns to SiteSummary overview tables

### PR DESCRIPTION
**Pull request by TaykYoku**
BEGINRELEASENOTES
Addressing the issues discussed in the #428.

NEW: Add columns to SiteSummary overview tables. 

ENDRELEASENOTES

### CODE REVIEW

**Comment by TaykYoku** [comment]
@phicharp please correct me if this is what you expected.

New columns added:
 - StatusType
 - Status

Знімок екрана 2021-03-23 о 16 00 41


Is that enough for a overview?

Also note that the first column has a color indicator of the general status of the element.

**Comment by phicharp** [comment]
Yes, this is what I was expecting! Clearly the first 2 columns only was not informative... I have noticed the color code matches the "Status" but this is nice...

**Comment by phicharp** [comment]
Did you also manage to fix the Data management plots for considering only the SEs connected with the site?

**Comment by TaykYoku** [comment]
> Did you also manage to fix the Data management plots for considering only the SEs connected with the site?

Yes, it should already be working properly

**Pull request merged**
