### PR TITLE
[v4r2] Add sweep, labeler and semantic CI configuration

### PR DESCRIPTION
**Pull request by chrisburr**
BEGINRELEASE

NEW: Add sweep, labeler and semantic CI configuration

ENDRELEASE

### CODE REVIEW

**Comment by chrisburr** [comment]
@TaykYoku As I don't have enough karma can you create the labels for the sweeping. I would be nice to match the colours used in vanilla DIRAC for consistency. The labels we need are:

* `sweep:from rel-v4r2`
* `sweep:from rel-v4r3`
* `alsoTargeting:rel-v4r3`
* `alsoTargeting:integration`
* `sweep:ignore`
* `sweep:failed`
* `sweep:done`

Once that's done can you add `alsoTargeting:rel-v4r3` to this PR (it'll be automatic for future PRs).

**Comment by TaykYoku** [comment]
@chrisburr Other than labels, do you need anything else to ready this?

**Comment by chrisburr** [comment]
@fstagni needs to add a secret to the GitHub configuration so the CI can add labels and create PRs. (I've pinged him privately about it)

**Comment by fstagni** [comment]
> @fstagni needs to add a secret to the GitHub configuration so the CI can add labels and create PRs. (I've pinged him privately about it)

done.

**Pull request merged**
