### PR TITLE
[v4r1] removed the compilation script (moved to management repo)

### PR DESCRIPTION
**Pull request by fstagni**
BEGINRELEASENOTES

NEW: removed the compilation script (moved to management repo)

ENDRELEASENOTES

### CODE REVIEW

**Comment by zmathe** [comment]
Lib/CompileTemplates/* are used to compile the JS. The files should moved to the management and the code should be adopted accordingly.

**Comment by fstagni** [comment]
Can you take care of that? I am not sure I understand what needs to be done.

**Comment by zmathe** [comment]
I will make the changes today.

**Comment by zmathe** [comment]
@fixed  in https://github.com/DIRACGrid/management/pull/7

**Review by zmathe — APPROVED** [review]

**Comment by zmathe** [comment]
@atsareg Could you please merge?

**Pull request merged**
