### PR TITLE
[v4r2] fix component monitoring

### PR DESCRIPTION
**Pull request by TaykYoku**
This RP fix "endless waiting for Accounting --> Monitoring/ComponentMonitoring filter" issue.

BEGINRELEASENOTES

Accounting:
FIX: delete the missing key 

ENDRELEASENOTES

### CODE REVIEW

**Review by fstagni — APPROVED** [review]

**Comment by TaykYoku** [comment]
restart tests

**Comment by chaen** [comment]
I assume it is because of the new `src` layout, but I don't understand why it is working for the other configuration, nor what is this third pyLint test. @fstagni can you look at it ? I think you setup that

**Comment by chaen** [comment]
ah actually the 2nd and 3rd pyLint test do nothing at all

**Comment by TaykYoku** [comment]
test issue fixed in #436

**Pull request closed without merging**
